version: '3'
services:
  db:
    image: mysql:8.0.32
    ports:
      - "3306:3306"
    env_file:
      - ../env/docker-compose.env
    container_name: seat-view
    environment:
      TZ: Asia/Seoul
    volumes:
      - seat-view:/var/lib/seat-view/db
      - ./my.cnf:/etc/mysql/my.cnf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./stadium.sql:/docker-entrypoint-initdb.d/stadium.sql
      - ./jamsil-seat-grade.sql:/docker-entrypoint-initdb.d/jamsil-seat-grade.sql
      - ./jamsil-seat-section.sql:/docker-entrypoint-initdb.d/jamsil-seat-section.sql
      - ./jamsil-seat.sql:/docker-entrypoint-initdb.d/jamsil-seat.sql
    restart: always

volumes:
  seat-view: