name: CD

on:
  push:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate environment file
        run: |
          mkdir -p env
          echo "${{secrets.DOCKER_COMPOSE_ENV}}" >> env/docker-compose.env
          echo "${{secrets.AWS_ENV}}" >> env/aws.env
          echo "${{secrets.DB_ENV}}" >> env/dev-db.env

      - name: Get execution permission to gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Build and push docker image
        run: |
          docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}
          docker build -t ${{secrets.DOCKERHUB_USERNAME}}/seat-view-reviews:latest .
          docker push ${{secrets.DOCKERHUB_USERNAME}}/seat-view-reviews:latest

      - name: Access AWS EC2 and run the app
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.EC2_HOST}}
          username: ${{secrets.EC2_USERNAME}}
          key: ${{secrets.EC2_KEY}}
          script: |
            scp -r ./env ${{secrets.EC2_USERNAME}}@${{secrets.EC2_HOST}}:~
            scp docker-compose.yml ${{secrets.EC2_USERNAME}}@${{secrets.EC2_HOST}}:~
            docker-compose stop
            docker-compose pull
            docker-compose up -d