name: CI

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate environment file
        run: |
          mkdir -p env
          echo "${{secrets.DOCKER_COMPOSE_ENV}}" >> env/docker-compose.env
          echo "${{secrets.AWS_ENV}}" >> env/aws.env
          echo "${{secrets.DB_ENV}}" >> env/dev-db.env
          echo "${{secrets.REDIS_ENV}}" >> env/redis.env

      - name: Run docker DB container
        run: docker-compose -f ./docker/docker-compose.yml up -d db

      - name: Get execution permission to gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build